version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: mysql_c
    restart: always
    volumes:
      - db-volume:/var/lib/mysql         
      - ./etudiants.sql:/docker-entrypoint-initdb.d/etudiants.sql
    environment:
      MYSQL_ROOT_PASSWORD: ing 
      MYSQL_DATABASE: ing             
      MYSQL_USER: ing                 
      MYSQL_PASSWORD: ing    
    

  app:
    image: ingapp
    container_name: ingapp_c
    restart: always
    volumes:
      - ./app:/var/www/html  
    ports:
      - 8084:80  
    depends_on:
      - db 
    
volumes:
  db-volume:  


